### ISSUE TITLE
Open discussion: Path to repo generated by "lenie init"

### ISSUE THREAD

**Issue by lamarpavel** [lamarpavel/lenie#8]
Currently the repo is initialized in myblog/git rather than myblog/.git as some would expect. I did that because I am used to bare repositories not being hidden. Opinions?

**Comment by Rehwanne** [comment]
Its the first time i see it this way, 
and my git complained until i copied it to .git

**Comment by JAEGER2K** [comment]
do you need to access .git/? -- no, thus there is no need for it.
this leads only to confusion.

**Comment by Rehwanne** [comment]
I cloned my own blog repo with git@server.srv:/blog which at first did not work because there was no .git directory in there. If you clone it with git@sever.srv:/blog/git i works as expected without a .git dir. I guess its meant this way, but im pretty sure its not the way you would usually expect things to get handled.

**Comment by lamarpavel** [comment]
True, it seems more natural to clone git@server.com/blog rather than git@server.com/blog/git, I will change the path to blog/.git and update the README soon.

**Comment by lamarpavel** [comment]
The current master is now using the proposed path of blog/.git. I have tested the new code and it should only affect newly created repositories and not break existing repos. Leave a message if things are broken for you.

**Comment by lamarpavel** [comment]
None of the test-blogs seem to have been broken by this, I thus consider it solved.
